name: test_app
description: "test in Tark"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  equatable: ^2.0.5
  web_socket_channel: ^3.0.0
  flutter_bloc: ^8.1.6
  get_it: ^7.6.0
  injectable: ^2.1.2
  google_fonts: ^6.2.1
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6


flutter:

  uses-material-design: true